# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindows.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHBoxLayout, QLabel, QLayout, QLineEdit,
    QMainWindow, QPlainTextEdit, QPushButton, QSizePolicy,
    QSpacerItem, QStackedWidget, QStatusBar, QTextEdit,
    QToolBox, QVBoxLayout, QWidget)
from  . import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 673)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(0, 10, 781, 611))
        self.two_split = QHBoxLayout(self.layoutWidget1)
        self.two_split.setObjectName(u"two_split")
        self.two_split.setContentsMargins(0, 0, 0, 0)
        self.Left_Component_Frame = QFrame(self.layoutWidget1)
        self.Left_Component_Frame.setObjectName(u"Left_Component_Frame")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left_Component_Frame.sizePolicy().hasHeightForWidth())
        self.Left_Component_Frame.setSizePolicy(sizePolicy)
        self.Left_Component_Frame.setFrameShape(QFrame.StyledPanel)
        self.Left_Component_Frame.setFrameShadow(QFrame.Raised)
        self.layoutWidget2 = QWidget(self.Left_Component_Frame)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(0, 0, 257, 301))
        self.verticalLayout = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton = QPushButton(self.layoutWidget2)
        self.pushButton.setObjectName(u"pushButton")
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy1)
        self.pushButton.setMinimumSize(QSize(125, 0))

        self.verticalLayout.addWidget(self.pushButton)

        self.function_button = QPushButton(self.layoutWidget2)
        self.function_button.setObjectName(u"function_button")
        sizePolicy1.setHeightForWidth(self.function_button.sizePolicy().hasHeightForWidth())
        self.function_button.setSizePolicy(sizePolicy1)
        self.function_button.setMinimumSize(QSize(125, 0))

        self.verticalLayout.addWidget(self.function_button)

        self.log_button = QPushButton(self.layoutWidget2)
        self.log_button.setObjectName(u"log_button")
        sizePolicy1.setHeightForWidth(self.log_button.sizePolicy().hasHeightForWidth())
        self.log_button.setSizePolicy(sizePolicy1)
        self.log_button.setMinimumSize(QSize(125, 0))

        self.verticalLayout.addWidget(self.log_button)

        self.setting_button = QPushButton(self.layoutWidget2)
        self.setting_button.setObjectName(u"setting_button")
        sizePolicy1.setHeightForWidth(self.setting_button.sizePolicy().hasHeightForWidth())
        self.setting_button.setSizePolicy(sizePolicy1)
        self.setting_button.setMinimumSize(QSize(125, 0))

        self.verticalLayout.addWidget(self.setting_button)


        self.two_split.addWidget(self.Left_Component_Frame)

        self.Right_Display_Frame = QFrame(self.layoutWidget1)
        self.Right_Display_Frame.setObjectName(u"Right_Display_Frame")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(5)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Right_Display_Frame.sizePolicy().hasHeightForWidth())
        self.Right_Display_Frame.setSizePolicy(sizePolicy2)
        self.Right_Display_Frame.setFrameShape(QFrame.StyledPanel)
        self.Right_Display_Frame.setFrameShadow(QFrame.Raised)
        self.stackedWidget = QStackedWidget(self.Right_Display_Frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(-1, -1, 641, 651))
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy3)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(103, 161, 281, 211))
        font = QFont()
        font.setFamilies([u"Agency FB"])
        font.setPointSize(48)
        self.label.setFont(font)
        self.stackedWidget.addWidget(self.page)
        self.function_page = QWidget()
        self.function_page.setObjectName(u"function_page")
        self.label_2 = QLabel(self.function_page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 271, 101))
        self.label_2.setFont(font)
        self.layoutWidget3 = QWidget(self.function_page)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(-10, 120, 651, 481))
        self.function_page_layout = QHBoxLayout(self.layoutWidget3)
        self.function_page_layout.setObjectName(u"function_page_layout")
        self.function_page_layout.setContentsMargins(0, 0, 0, 0)
        self.function_list = QFrame(self.layoutWidget3)
        self.function_list.setObjectName(u"function_list")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy4.setHorizontalStretch(1)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.function_list.sizePolicy().hasHeightForWidth())
        self.function_list.setSizePolicy(sizePolicy4)
        self.function_list.setAutoFillBackground(False)
        self.function_list.setFrameShape(QFrame.StyledPanel)
        self.function_list.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget = QWidget(self.function_list)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 0, 321, 481))
        self.functionListLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.functionListLayout.setSpacing(0)
        self.functionListLayout.setObjectName(u"functionListLayout")
        self.functionListLayout.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.functionListLayout.setContentsMargins(0, 0, 0, 0)
        self.DisableWinFrame = QFrame(self.verticalLayoutWidget)
        self.DisableWinFrame.setObjectName(u"DisableWinFrame")
        sizePolicy5 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.DisableWinFrame.sizePolicy().hasHeightForWidth())
        self.DisableWinFrame.setSizePolicy(sizePolicy5)
        self.DisableWinFrame.setMaximumSize(QSize(16777215, 100))
        self.DisableWinFrame.setFrameShape(QFrame.StyledPanel)
        self.DisableWinFrame.setFrameShadow(QFrame.Raised)
        self.disable_win_start_button = QPushButton(self.DisableWinFrame)
        self.disable_win_start_button.setObjectName(u"disable_win_start_button")
        self.disable_win_start_button.setGeometry(QRect(160, 10, 121, 51))
        self.disable_win_button = QPushButton(self.DisableWinFrame)
        self.disable_win_button.setObjectName(u"disable_win_button")
        self.disable_win_button.setGeometry(QRect(0, 10, 111, 51))
        sizePolicy6 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.disable_win_button.sizePolicy().hasHeightForWidth())
        self.disable_win_button.setSizePolicy(sizePolicy6)
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(12)
        self.disable_win_button.setFont(font1)
        self.disable_win_button.setFlat(True)
        self.disable_win_online_icon = QLabel(self.DisableWinFrame)
        self.disable_win_online_icon.setObjectName(u"disable_win_online_icon")
        self.disable_win_online_icon.setEnabled(True)
        self.disable_win_online_icon.setGeometry(QRect(120, 20, 50, 50))
        self.disable_win_online_icon.setPixmap(QPixmap(u":/icon/images/online.png"))
        self.disable_win_online_icon.setScaledContents(True)
        self.disable_win_offline_icon = QLabel(self.DisableWinFrame)
        self.disable_win_offline_icon.setObjectName(u"disable_win_offline_icon")
        self.disable_win_offline_icon.setEnabled(True)
        self.disable_win_offline_icon.setGeometry(QRect(120, 20, 50, 50))
        self.disable_win_offline_icon.setPixmap(QPixmap(u":/icon/images/offline.png"))
        self.disable_win_offline_icon.setScaledContents(True)
        self.disable_win_quit_button = QPushButton(self.DisableWinFrame)
        self.disable_win_quit_button.setObjectName(u"disable_win_quit_button")
        self.disable_win_quit_button.setGeometry(QRect(160, 10, 121, 51))

        self.functionListLayout.addWidget(self.DisableWinFrame)

        self.QQMonitorFrame = QFrame(self.verticalLayoutWidget)
        self.QQMonitorFrame.setObjectName(u"QQMonitorFrame")
        sizePolicy5.setHeightForWidth(self.QQMonitorFrame.sizePolicy().hasHeightForWidth())
        self.QQMonitorFrame.setSizePolicy(sizePolicy5)
        self.QQMonitorFrame.setMaximumSize(QSize(16777215, 100))
        self.QQMonitorFrame.setFrameShape(QFrame.StyledPanel)
        self.QQMonitorFrame.setFrameShadow(QFrame.Raised)
        self.qq_monitor_start_button = QPushButton(self.QQMonitorFrame)
        self.qq_monitor_start_button.setObjectName(u"qq_monitor_start_button")
        self.qq_monitor_start_button.setGeometry(QRect(160, 10, 121, 51))
        self.qq_monitor_button = QPushButton(self.QQMonitorFrame)
        self.qq_monitor_button.setObjectName(u"qq_monitor_button")
        self.qq_monitor_button.setGeometry(QRect(0, 10, 111, 51))
        sizePolicy6.setHeightForWidth(self.qq_monitor_button.sizePolicy().hasHeightForWidth())
        self.qq_monitor_button.setSizePolicy(sizePolicy6)
        self.qq_monitor_button.setFont(font1)
        self.qq_monitor_button.setFlat(True)
        self.qq_monitor_online_icon = QLabel(self.QQMonitorFrame)
        self.qq_monitor_online_icon.setObjectName(u"qq_monitor_online_icon")
        self.qq_monitor_online_icon.setEnabled(True)
        self.qq_monitor_online_icon.setGeometry(QRect(120, 20, 50, 50))
        self.qq_monitor_online_icon.setPixmap(QPixmap(u":/icon/images/online.png"))
        self.qq_monitor_online_icon.setScaledContents(True)
        self.qq_monitor_offline_icon = QLabel(self.QQMonitorFrame)
        self.qq_monitor_offline_icon.setObjectName(u"qq_monitor_offline_icon")
        self.qq_monitor_offline_icon.setEnabled(True)
        self.qq_monitor_offline_icon.setGeometry(QRect(120, 20, 50, 50))
        self.qq_monitor_offline_icon.setPixmap(QPixmap(u":/icon/images/offline.png"))
        self.qq_monitor_offline_icon.setScaledContents(True)
        self.qq_monitor_quit_button = QPushButton(self.QQMonitorFrame)
        self.qq_monitor_quit_button.setObjectName(u"qq_monitor_quit_button")
        self.qq_monitor_quit_button.setGeometry(QRect(160, 10, 121, 51))

        self.functionListLayout.addWidget(self.QQMonitorFrame)

        self.EveryDayFrame = QFrame(self.verticalLayoutWidget)
        self.EveryDayFrame.setObjectName(u"EveryDayFrame")
        sizePolicy5.setHeightForWidth(self.EveryDayFrame.sizePolicy().hasHeightForWidth())
        self.EveryDayFrame.setSizePolicy(sizePolicy5)
        self.EveryDayFrame.setMaximumSize(QSize(16777215, 100))
        self.EveryDayFrame.setFrameShape(QFrame.StyledPanel)
        self.EveryDayFrame.setFrameShadow(QFrame.Raised)
        self.every_day_status_button = QPushButton(self.EveryDayFrame)
        self.every_day_status_button.setObjectName(u"every_day_status_button")
        self.every_day_status_button.setEnabled(False)
        self.every_day_status_button.setGeometry(QRect(160, 10, 121, 51))
        self.every_day_button = QPushButton(self.EveryDayFrame)
        self.every_day_button.setObjectName(u"every_day_button")
        self.every_day_button.setGeometry(QRect(0, 10, 111, 51))
        sizePolicy6.setHeightForWidth(self.every_day_button.sizePolicy().hasHeightForWidth())
        self.every_day_button.setSizePolicy(sizePolicy6)
        self.every_day_button.setFont(font1)
        self.every_day_button.setFlat(True)
        self.every_day_online_icon = QLabel(self.EveryDayFrame)
        self.every_day_online_icon.setObjectName(u"every_day_online_icon")
        self.every_day_online_icon.setEnabled(True)
        self.every_day_online_icon.setGeometry(QRect(120, 20, 50, 50))
        self.every_day_online_icon.setPixmap(QPixmap(u":/icon/images/online.png"))
        self.every_day_online_icon.setScaledContents(True)
        self.every_day_offline_icon = QLabel(self.EveryDayFrame)
        self.every_day_offline_icon.setObjectName(u"every_day_offline_icon")
        self.every_day_offline_icon.setEnabled(True)
        self.every_day_offline_icon.setGeometry(QRect(120, 20, 50, 50))
        self.every_day_offline_icon.setPixmap(QPixmap(u":/icon/images/offline.png"))
        self.every_day_offline_icon.setScaledContents(True)

        self.functionListLayout.addWidget(self.EveryDayFrame)

        self.VoiceRecognizeFrame = QFrame(self.verticalLayoutWidget)
        self.VoiceRecognizeFrame.setObjectName(u"VoiceRecognizeFrame")
        sizePolicy5.setHeightForWidth(self.VoiceRecognizeFrame.sizePolicy().hasHeightForWidth())
        self.VoiceRecognizeFrame.setSizePolicy(sizePolicy5)
        self.VoiceRecognizeFrame.setMaximumSize(QSize(16777215, 100))
        self.VoiceRecognizeFrame.setFrameShape(QFrame.StyledPanel)
        self.VoiceRecognizeFrame.setFrameShadow(QFrame.Raised)
        self.voice_recognize_start_button = QPushButton(self.VoiceRecognizeFrame)
        self.voice_recognize_start_button.setObjectName(u"voice_recognize_start_button")
        self.voice_recognize_start_button.setEnabled(True)
        self.voice_recognize_start_button.setGeometry(QRect(160, 10, 121, 51))
        self.voice_recognize_button = QPushButton(self.VoiceRecognizeFrame)
        self.voice_recognize_button.setObjectName(u"voice_recognize_button")
        self.voice_recognize_button.setGeometry(QRect(0, 10, 111, 51))
        sizePolicy6.setHeightForWidth(self.voice_recognize_button.sizePolicy().hasHeightForWidth())
        self.voice_recognize_button.setSizePolicy(sizePolicy6)
        self.voice_recognize_button.setFont(font1)
        self.voice_recognize_button.setFlat(True)
        self.voice_recognize_online_icon = QLabel(self.VoiceRecognizeFrame)
        self.voice_recognize_online_icon.setObjectName(u"voice_recognize_online_icon")
        self.voice_recognize_online_icon.setEnabled(True)
        self.voice_recognize_online_icon.setGeometry(QRect(120, 20, 50, 50))
        self.voice_recognize_online_icon.setPixmap(QPixmap(u":/icon/images/online.png"))
        self.voice_recognize_online_icon.setScaledContents(True)
        self.voice_recognize_offline_icon = QLabel(self.VoiceRecognizeFrame)
        self.voice_recognize_offline_icon.setObjectName(u"voice_recognize_offline_icon")
        self.voice_recognize_offline_icon.setEnabled(True)
        self.voice_recognize_offline_icon.setGeometry(QRect(120, 20, 50, 50))
        self.voice_recognize_offline_icon.setPixmap(QPixmap(u":/icon/images/offline.png"))
        self.voice_recognize_offline_icon.setScaledContents(True)
        self.voice_recognize_quit_button = QPushButton(self.VoiceRecognizeFrame)
        self.voice_recognize_quit_button.setObjectName(u"voice_recognize_quit_button")
        self.voice_recognize_quit_button.setEnabled(True)
        self.voice_recognize_quit_button.setGeometry(QRect(160, 10, 121, 51))

        self.functionListLayout.addWidget(self.VoiceRecognizeFrame)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.functionListLayout.addItem(self.verticalSpacer_2)


        self.function_page_layout.addWidget(self.function_list)

        self.function_display = QFrame(self.layoutWidget3)
        self.function_display.setObjectName(u"function_display")
        sizePolicy7 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy7.setHorizontalStretch(1)
        sizePolicy7.setVerticalStretch(1)
        sizePolicy7.setHeightForWidth(self.function_display.sizePolicy().hasHeightForWidth())
        self.function_display.setSizePolicy(sizePolicy7)
        self.function_display.setAutoFillBackground(False)
        self.function_display.setFrameShape(QFrame.StyledPanel)
        self.function_display.setFrameShadow(QFrame.Raised)
        self.function_widget = QStackedWidget(self.function_display)
        self.function_widget.setObjectName(u"function_widget")
        self.function_widget.setGeometry(QRect(-10, 0, 331, 481))
        sizePolicy7.setHeightForWidth(self.function_widget.sizePolicy().hasHeightForWidth())
        self.function_widget.setSizePolicy(sizePolicy7)
        self.disable_win_page = QWidget()
        self.disable_win_page.setObjectName(u"disable_win_page")
        sizePolicy7.setHeightForWidth(self.disable_win_page.sizePolicy().hasHeightForWidth())
        self.disable_win_page.setSizePolicy(sizePolicy7)
        self.toolBox = QToolBox(self.disable_win_page)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(8, 20, 311, 431))
        sizePolicy7.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy7)
        font2 = QFont()
        font2.setFamilies([u"Agency FB"])
        font2.setPointSize(12)
        self.toolBox.setFont(font2)
        self.disable_win_describe_page = QWidget()
        self.disable_win_describe_page.setObjectName(u"disable_win_describe_page")
        self.disable_win_describe_page.setGeometry(QRect(0, 0, 100, 30))
        self.disable_win_function_title = QLabel(self.disable_win_describe_page)
        self.disable_win_function_title.setObjectName(u"disable_win_function_title")
        self.disable_win_function_title.setGeometry(QRect(0, 10, 291, 41))
        font3 = QFont()
        font3.setFamilies([u"\u534e\u6587\u6977\u4f53"])
        font3.setPointSize(18)
        font3.setBold(True)
        self.disable_win_function_title.setFont(font3)
        self.disable_win_function_describe = QTextEdit(self.disable_win_describe_page)
        self.disable_win_function_describe.setObjectName(u"disable_win_function_describe")
        self.disable_win_function_describe.setGeometry(QRect(10, 70, 281, 271))
        self.disable_win_function_describe.setReadOnly(True)
        self.toolBox.addItem(self.disable_win_describe_page, u"\u529f\u80fd\u8bf4\u660e")
        self.disable_win_config_page = QWidget()
        self.disable_win_config_page.setObjectName(u"disable_win_config_page")
        self.disable_win_config_page.setGeometry(QRect(0, 0, 311, 369))
        self.verticalLayoutWidget_3 = QWidget(self.disable_win_config_page)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 10, 291, 351))
        self.Config_Page_Layout = QVBoxLayout(self.verticalLayoutWidget_3)
        self.Config_Page_Layout.setObjectName(u"Config_Page_Layout")
        self.Config_Page_Layout.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.Config_Page_Layout.setContentsMargins(0, 0, 0, 0)
        self.disable_win_startup_check = QCheckBox(self.verticalLayoutWidget_3)
        self.disable_win_startup_check.setObjectName(u"disable_win_startup_check")
        sizePolicy8 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.disable_win_startup_check.sizePolicy().hasHeightForWidth())
        self.disable_win_startup_check.setSizePolicy(sizePolicy8)
        self.disable_win_startup_check.setMinimumSize(QSize(0, 0))
        self.disable_win_startup_check.setMaximumSize(QSize(16777215, 60))

        self.Config_Page_Layout.addWidget(self.disable_win_startup_check)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.Config_Page_Layout.addItem(self.verticalSpacer)

        self.toolBox.addItem(self.disable_win_config_page, u"\u57fa\u672c\u914d\u7f6e")
        self.function_widget.addWidget(self.disable_win_page)
        self.qq_monitor_page = QWidget()
        self.qq_monitor_page.setObjectName(u"qq_monitor_page")
        sizePolicy7.setHeightForWidth(self.qq_monitor_page.sizePolicy().hasHeightForWidth())
        self.qq_monitor_page.setSizePolicy(sizePolicy7)
        self.toolBox_2 = QToolBox(self.qq_monitor_page)
        self.toolBox_2.setObjectName(u"toolBox_2")
        self.toolBox_2.setGeometry(QRect(8, 20, 311, 431))
        sizePolicy7.setHeightForWidth(self.toolBox_2.sizePolicy().hasHeightForWidth())
        self.toolBox_2.setSizePolicy(sizePolicy7)
        self.toolBox_2.setFont(font2)
        self.qq_monitor_describe_page = QWidget()
        self.qq_monitor_describe_page.setObjectName(u"qq_monitor_describe_page")
        self.qq_monitor_describe_page.setGeometry(QRect(0, 0, 100, 30))
        self.qq_monitor_function_title = QLabel(self.qq_monitor_describe_page)
        self.qq_monitor_function_title.setObjectName(u"qq_monitor_function_title")
        self.qq_monitor_function_title.setGeometry(QRect(0, 10, 301, 41))
        self.qq_monitor_function_title.setFont(font3)
        self.qq_monitor_function_describe = QTextEdit(self.qq_monitor_describe_page)
        self.qq_monitor_function_describe.setObjectName(u"qq_monitor_function_describe")
        self.qq_monitor_function_describe.setGeometry(QRect(10, 70, 281, 271))
        self.qq_monitor_function_describe.setReadOnly(True)
        self.toolBox_2.addItem(self.qq_monitor_describe_page, u"\u529f\u80fd\u8bf4\u660e")
        self.qq_monitor_config_page = QWidget()
        self.qq_monitor_config_page.setObjectName(u"qq_monitor_config_page")
        self.qq_monitor_config_page.setGeometry(QRect(0, 0, 311, 363))
        self.verticalLayoutWidget_4 = QWidget(self.qq_monitor_config_page)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(10, 10, 291, 351))
        self.Config_Page_Layout_2 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.Config_Page_Layout_2.setObjectName(u"Config_Page_Layout_2")
        self.Config_Page_Layout_2.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.Config_Page_Layout_2.setContentsMargins(0, 0, 0, 0)
        self.qq_monitor_startup_check = QCheckBox(self.verticalLayoutWidget_4)
        self.qq_monitor_startup_check.setObjectName(u"qq_monitor_startup_check")
        sizePolicy8.setHeightForWidth(self.qq_monitor_startup_check.sizePolicy().hasHeightForWidth())
        self.qq_monitor_startup_check.setSizePolicy(sizePolicy8)
        self.qq_monitor_startup_check.setMinimumSize(QSize(0, 0))
        self.qq_monitor_startup_check.setMaximumSize(QSize(16777215, 60))

        self.Config_Page_Layout_2.addWidget(self.qq_monitor_startup_check)

        self.qq_monitor_address = QFrame(self.verticalLayoutWidget_4)
        self.qq_monitor_address.setObjectName(u"qq_monitor_address")
        sizePolicy9 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
        sizePolicy9.setHorizontalStretch(1)
        sizePolicy9.setVerticalStretch(1)
        sizePolicy9.setHeightForWidth(self.qq_monitor_address.sizePolicy().hasHeightForWidth())
        self.qq_monitor_address.setSizePolicy(sizePolicy9)
        self.qq_monitor_address.setMinimumSize(QSize(0, 60))
        self.qq_monitor_address.setMaximumSize(QSize(16777215, 60))
        self.qq_monitor_address.setSizeIncrement(QSize(0, 90))
        self.qq_monitor_address.setBaseSize(QSize(0, 90))
        self.qq_monitor_address.setFrameShape(QFrame.StyledPanel)
        self.qq_monitor_address.setFrameShadow(QFrame.Raised)
        self.qq_monitor_address_title = QLabel(self.qq_monitor_address)
        self.qq_monitor_address_title.setObjectName(u"qq_monitor_address_title")
        self.qq_monitor_address_title.setGeometry(QRect(0, 20, 70, 25))
        self.qq_monitor_address_edit = QLineEdit(self.qq_monitor_address)
        self.qq_monitor_address_edit.setObjectName(u"qq_monitor_address_edit")
        self.qq_monitor_address_edit.setGeometry(QRect(90, 15, 191, 30))

        self.Config_Page_Layout_2.addWidget(self.qq_monitor_address)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.Config_Page_Layout_2.addItem(self.verticalSpacer_3)

        self.toolBox_2.addItem(self.qq_monitor_config_page, u"\u57fa\u672c\u914d\u7f6e")
        self.function_widget.addWidget(self.qq_monitor_page)
        self.every_day_page = QWidget()
        self.every_day_page.setObjectName(u"every_day_page")
        self.toolBox_3 = QToolBox(self.every_day_page)
        self.toolBox_3.setObjectName(u"toolBox_3")
        self.toolBox_3.setGeometry(QRect(8, 20, 311, 431))
        sizePolicy7.setHeightForWidth(self.toolBox_3.sizePolicy().hasHeightForWidth())
        self.toolBox_3.setSizePolicy(sizePolicy7)
        self.toolBox_3.setFont(font2)
        self.every_day_describe_page = QWidget()
        self.every_day_describe_page.setObjectName(u"every_day_describe_page")
        self.every_day_describe_page.setGeometry(QRect(0, 0, 100, 30))
        self.every_day_function_title = QLabel(self.every_day_describe_page)
        self.every_day_function_title.setObjectName(u"every_day_function_title")
        self.every_day_function_title.setGeometry(QRect(0, 10, 301, 41))
        self.every_day_function_title.setFont(font3)
        self.every_day_function_describe = QTextEdit(self.every_day_describe_page)
        self.every_day_function_describe.setObjectName(u"every_day_function_describe")
        self.every_day_function_describe.setGeometry(QRect(10, 70, 281, 271))
        self.every_day_function_describe.setReadOnly(True)
        self.toolBox_3.addItem(self.every_day_describe_page, u"\u529f\u80fd\u8bf4\u660e")
        self.every_day_config_page = QWidget()
        self.every_day_config_page.setObjectName(u"every_day_config_page")
        self.every_day_config_page.setGeometry(QRect(0, 0, 311, 363))
        self.verticalLayoutWidget_6 = QWidget(self.every_day_config_page)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(10, 10, 291, 351))
        self.Config_Page_Layout_4 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.Config_Page_Layout_4.setObjectName(u"Config_Page_Layout_4")
        self.Config_Page_Layout_4.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.Config_Page_Layout_4.setContentsMargins(0, 0, 0, 0)
        self.every_day_startup_check = QCheckBox(self.verticalLayoutWidget_6)
        self.every_day_startup_check.setObjectName(u"every_day_startup_check")
        sizePolicy8.setHeightForWidth(self.every_day_startup_check.sizePolicy().hasHeightForWidth())
        self.every_day_startup_check.setSizePolicy(sizePolicy8)
        self.every_day_startup_check.setMinimumSize(QSize(0, 0))
        self.every_day_startup_check.setMaximumSize(QSize(16777215, 60))

        self.Config_Page_Layout_4.addWidget(self.every_day_startup_check)

        self.blog_online_startup_check = QCheckBox(self.verticalLayoutWidget_6)
        self.blog_online_startup_check.setObjectName(u"blog_online_startup_check")
        sizePolicy8.setHeightForWidth(self.blog_online_startup_check.sizePolicy().hasHeightForWidth())
        self.blog_online_startup_check.setSizePolicy(sizePolicy8)
        self.blog_online_startup_check.setMinimumSize(QSize(0, 0))
        self.blog_online_startup_check.setMaximumSize(QSize(16777215, 60))

        self.Config_Page_Layout_4.addWidget(self.blog_online_startup_check)

        self.verticalSpacer_5 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.Config_Page_Layout_4.addItem(self.verticalSpacer_5)

        self.toolBox_3.addItem(self.every_day_config_page, u"\u57fa\u672c\u914d\u7f6e")
        self.function_widget.addWidget(self.every_day_page)
        self.voice_recognize_page = QWidget()
        self.voice_recognize_page.setObjectName(u"voice_recognize_page")
        self.toolBox_4 = QToolBox(self.voice_recognize_page)
        self.toolBox_4.setObjectName(u"toolBox_4")
        self.toolBox_4.setGeometry(QRect(8, 20, 311, 431))
        sizePolicy7.setHeightForWidth(self.toolBox_4.sizePolicy().hasHeightForWidth())
        self.toolBox_4.setSizePolicy(sizePolicy7)
        self.toolBox_4.setFont(font2)
        self.voice_recognize_describe_page = QWidget()
        self.voice_recognize_describe_page.setObjectName(u"voice_recognize_describe_page")
        self.voice_recognize_describe_page.setGeometry(QRect(0, 0, 311, 363))
        self.voice_recognize_function_title = QLabel(self.voice_recognize_describe_page)
        self.voice_recognize_function_title.setObjectName(u"voice_recognize_function_title")
        self.voice_recognize_function_title.setGeometry(QRect(0, 10, 301, 41))
        self.voice_recognize_function_title.setFont(font3)
        self.voice_recognize_function_describe = QTextEdit(self.voice_recognize_describe_page)
        self.voice_recognize_function_describe.setObjectName(u"voice_recognize_function_describe")
        self.voice_recognize_function_describe.setGeometry(QRect(10, 70, 281, 271))
        self.voice_recognize_function_describe.setReadOnly(True)
        self.toolBox_4.addItem(self.voice_recognize_describe_page, u"\u529f\u80fd\u8bf4\u660e")
        self.voice_recognize_config_page = QWidget()
        self.voice_recognize_config_page.setObjectName(u"voice_recognize_config_page")
        self.voice_recognize_config_page.setGeometry(QRect(0, 0, 311, 363))
        self.verticalLayoutWidget_7 = QWidget(self.voice_recognize_config_page)
        self.verticalLayoutWidget_7.setObjectName(u"verticalLayoutWidget_7")
        self.verticalLayoutWidget_7.setGeometry(QRect(10, 10, 291, 351))
        self.Config_Page_Layout_5 = QVBoxLayout(self.verticalLayoutWidget_7)
        self.Config_Page_Layout_5.setObjectName(u"Config_Page_Layout_5")
        self.Config_Page_Layout_5.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.Config_Page_Layout_5.setContentsMargins(0, 0, 0, 0)
        self.voice_recognize_startup_check = QCheckBox(self.verticalLayoutWidget_7)
        self.voice_recognize_startup_check.setObjectName(u"voice_recognize_startup_check")
        sizePolicy8.setHeightForWidth(self.voice_recognize_startup_check.sizePolicy().hasHeightForWidth())
        self.voice_recognize_startup_check.setSizePolicy(sizePolicy8)
        self.voice_recognize_startup_check.setMinimumSize(QSize(0, 0))
        self.voice_recognize_startup_check.setMaximumSize(QSize(16777215, 60))

        self.Config_Page_Layout_5.addWidget(self.voice_recognize_startup_check)

        self.device_choose_frame = QFrame(self.verticalLayoutWidget_7)
        self.device_choose_frame.setObjectName(u"device_choose_frame")
        sizePolicy10 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.device_choose_frame.sizePolicy().hasHeightForWidth())
        self.device_choose_frame.setSizePolicy(sizePolicy10)
        self.device_choose_frame.setMinimumSize(QSize(289, 60))
        self.device_choose_frame.setFrameShape(QFrame.StyledPanel)
        self.device_choose_frame.setFrameShadow(QFrame.Raised)
        self.device_choose_label = QLabel(self.device_choose_frame)
        self.device_choose_label.setObjectName(u"device_choose_label")
        self.device_choose_label.setGeometry(QRect(0, 20, 81, 31))
        font4 = QFont()
        font4.setFamilies([u"\u65b0\u5b8b\u4f53"])
        font4.setPointSize(10)
        self.device_choose_label.setFont(font4)
        self.device_choose_combo_box = QComboBox(self.device_choose_frame)
        self.device_choose_combo_box.setObjectName(u"device_choose_combo_box")
        self.device_choose_combo_box.setGeometry(QRect(90, 20, 191, 30))

        self.Config_Page_Layout_5.addWidget(self.device_choose_frame)

        self.ak_id = QFrame(self.verticalLayoutWidget_7)
        self.ak_id.setObjectName(u"ak_id")
        sizePolicy9.setHeightForWidth(self.ak_id.sizePolicy().hasHeightForWidth())
        self.ak_id.setSizePolicy(sizePolicy9)
        self.ak_id.setMinimumSize(QSize(0, 60))
        self.ak_id.setMaximumSize(QSize(16777215, 60))
        self.ak_id.setSizeIncrement(QSize(0, 90))
        self.ak_id.setBaseSize(QSize(0, 90))
        self.ak_id.setFrameShape(QFrame.StyledPanel)
        self.ak_id.setFrameShadow(QFrame.Raised)
        self.ak_id_title = QLabel(self.ak_id)
        self.ak_id_title.setObjectName(u"ak_id_title")
        self.ak_id_title.setGeometry(QRect(0, 20, 85, 25))
        font5 = QFont()
        font5.setFamilies([u"Microsoft JhengHei UI"])
        self.ak_id_title.setFont(font5)
        self.ak_id_title.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ak_id_edit = QLineEdit(self.ak_id)
        self.ak_id_edit.setObjectName(u"ak_id_edit")
        self.ak_id_edit.setGeometry(QRect(90, 15, 191, 30))
        self.ak_id_edit.setEchoMode(QLineEdit.Password)
        self.ak_id_edit.setClearButtonEnabled(False)

        self.Config_Page_Layout_5.addWidget(self.ak_id)

        self.ak_secret = QFrame(self.verticalLayoutWidget_7)
        self.ak_secret.setObjectName(u"ak_secret")
        sizePolicy9.setHeightForWidth(self.ak_secret.sizePolicy().hasHeightForWidth())
        self.ak_secret.setSizePolicy(sizePolicy9)
        self.ak_secret.setMinimumSize(QSize(0, 60))
        self.ak_secret.setMaximumSize(QSize(16777215, 60))
        self.ak_secret.setSizeIncrement(QSize(0, 90))
        self.ak_secret.setBaseSize(QSize(0, 90))
        self.ak_secret.setFrameShape(QFrame.StyledPanel)
        self.ak_secret.setFrameShadow(QFrame.Raised)
        self.ak_secret_title = QLabel(self.ak_secret)
        self.ak_secret_title.setObjectName(u"ak_secret_title")
        self.ak_secret_title.setGeometry(QRect(0, 20, 85, 25))
        self.ak_secret_title.setFont(font5)
        self.ak_secret_title.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ak_secret_edit = QLineEdit(self.ak_secret)
        self.ak_secret_edit.setObjectName(u"ak_secret_edit")
        self.ak_secret_edit.setGeometry(QRect(90, 15, 191, 30))
        self.ak_secret_edit.setEchoMode(QLineEdit.Password)
        self.ak_secret_edit.setClearButtonEnabled(False)

        self.Config_Page_Layout_5.addWidget(self.ak_secret)

        self.app_key = QFrame(self.verticalLayoutWidget_7)
        self.app_key.setObjectName(u"app_key")
        sizePolicy9.setHeightForWidth(self.app_key.sizePolicy().hasHeightForWidth())
        self.app_key.setSizePolicy(sizePolicy9)
        self.app_key.setMinimumSize(QSize(0, 60))
        self.app_key.setMaximumSize(QSize(16777215, 60))
        self.app_key.setSizeIncrement(QSize(0, 90))
        self.app_key.setBaseSize(QSize(0, 90))
        self.app_key.setFrameShape(QFrame.StyledPanel)
        self.app_key.setFrameShadow(QFrame.Raised)
        self.app_key_title = QLabel(self.app_key)
        self.app_key_title.setObjectName(u"app_key_title")
        self.app_key_title.setGeometry(QRect(0, 20, 85, 25))
        self.app_key_title.setFont(font5)
        self.app_key_title.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.app_key_edit = QLineEdit(self.app_key)
        self.app_key_edit.setObjectName(u"app_key_edit")
        self.app_key_edit.setGeometry(QRect(90, 15, 191, 30))
        self.app_key_edit.setEchoMode(QLineEdit.Password)
        self.app_key_edit.setClearButtonEnabled(False)

        self.Config_Page_Layout_5.addWidget(self.app_key)

        self.verticalSpacer_6 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.Config_Page_Layout_5.addItem(self.verticalSpacer_6)

        self.toolBox_4.addItem(self.voice_recognize_config_page, u"\u57fa\u672c\u914d\u7f6e")
        self.function_widget.addWidget(self.voice_recognize_page)

        self.function_page_layout.addWidget(self.function_display)

        self.stackedWidget.addWidget(self.function_page)
        self.log_page = QWidget()
        self.log_page.setObjectName(u"log_page")
        self.LogTextArea = QPlainTextEdit(self.log_page)
        self.LogTextArea.setObjectName(u"LogTextArea")
        self.LogTextArea.setGeometry(QRect(23, 60, 601, 571))
        font6 = QFont()
        font6.setFamilies([u"\u5b8b\u4f53"])
        font6.setPointSize(11)
        self.LogTextArea.setFont(font6)
        self.LogTextArea.setReadOnly(True)
        self.stackedWidget.addWidget(self.log_page)
        self.setting_page = QWidget()
        self.setting_page.setObjectName(u"setting_page")
        self.verticalLayoutWidget_2 = QWidget(self.setting_page)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(40, 90, 201, 491))
        self.setting_layout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.setting_layout.setObjectName(u"setting_layout")
        self.setting_layout.setContentsMargins(0, 0, 0, 0)
        self.auto_start_checkbox = QCheckBox(self.verticalLayoutWidget_2)
        self.auto_start_checkbox.setObjectName(u"auto_start_checkbox")

        self.setting_layout.addWidget(self.auto_start_checkbox)

        self.stackedWidget.addWidget(self.setting_page)

        self.two_split.addWidget(self.Right_Display_Frame)

        self.Button_Display_Frame = QFrame(self.centralwidget)
        self.Button_Display_Frame.setObjectName(u"Button_Display_Frame")
        self.Button_Display_Frame.setGeometry(QRect(0, 620, 781, 31))
        self.Button_Display_Frame.setFrameShape(QFrame.StyledPanel)
        self.Button_Display_Frame.setFrameShadow(QFrame.Raised)
        self.version_label = QLabel(self.Button_Display_Frame)
        self.version_label.setObjectName(u"version_label")
        self.version_label.setGeometry(QRect(710, 0, 61, 31))
        sizePolicy11 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy11.setHorizontalStretch(0)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.version_label.sizePolicy().hasHeightForWidth())
        self.version_label.setSizePolicy(sizePolicy11)
        font7 = QFont()
        font7.setFamilies([u"Nirmala UI"])
        font7.setPointSize(16)
        self.version_label.setFont(font7)
        self.version_label.setAlignment(Qt.AlignCenter)
        self.version_update_button = QPushButton(self.Button_Display_Frame)
        self.version_update_button.setObjectName(u"version_update_button")
        self.version_update_button.setGeometry(QRect(580, 0, 111, 31))
        sizePolicy10.setHeightForWidth(self.version_update_button.sizePolicy().hasHeightForWidth())
        self.version_update_button.setSizePolicy(sizePolicy10)
        self.version_update_button.setMinimumSize(QSize(0, 0))
        self.version_update_button.setBaseSize(QSize(0, 203))
        self.check_update_button = QPushButton(self.Button_Display_Frame)
        self.check_update_button.setObjectName(u"check_update_button")
        self.check_update_button.setEnabled(True)
        self.check_update_button.setGeometry(QRect(580, 0, 111, 31))
        sizePolicy10.setHeightForWidth(self.check_update_button.sizePolicy().hasHeightForWidth())
        self.check_update_button.setSizePolicy(sizePolicy10)
        self.check_update_button.setMinimumSize(QSize(0, 0))
        self.check_update_button.setBaseSize(QSize(0, 203))
        self.check_update_button.setCheckable(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.disable_win_button.setDefault(False)
        self.qq_monitor_button.setDefault(False)
        self.every_day_button.setDefault(False)
        self.voice_recognize_button.setDefault(False)
        self.function_widget.setCurrentIndex(3)
        self.toolBox.setCurrentIndex(1)
        self.toolBox.layout().setSpacing(3)
        self.toolBox_2.setCurrentIndex(1)
        self.toolBox_2.layout().setSpacing(6)
        self.toolBox_3.setCurrentIndex(1)
        self.toolBox_3.layout().setSpacing(6)
        self.toolBox_4.setCurrentIndex(1)
        self.toolBox_4.layout().setSpacing(6)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u9875\u97621", None))
        self.function_button.setText(QCoreApplication.translate("MainWindow", u"\u529f\u80fd", None))
        self.log_button.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u5fd7", None))
        self.setting_button.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u754c\u97621", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u5217\u8868", None))
        self.disable_win_start_button.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.disable_win_button.setText(QCoreApplication.translate("MainWindow", u"\u7981\u7528Win", None))
        self.disable_win_online_icon.setText("")
        self.disable_win_offline_icon.setText("")
        self.disable_win_quit_button.setText(QCoreApplication.translate("MainWindow", u"QUIT", None))
        self.qq_monitor_start_button.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.qq_monitor_button.setText(QCoreApplication.translate("MainWindow", u"QQ\u76d1\u542c", None))
        self.qq_monitor_online_icon.setText("")
        self.qq_monitor_offline_icon.setText("")
        self.qq_monitor_quit_button.setText(QCoreApplication.translate("MainWindow", u"QUIT", None))
        self.every_day_status_button.setText(QCoreApplication.translate("MainWindow", u"\u5df2\u5b8c\u6210", None))
        self.every_day_button.setText(QCoreApplication.translate("MainWindow", u"\u6bcf\u65e5\u68c0\u67e5", None))
        self.every_day_online_icon.setText("")
        self.every_day_offline_icon.setText("")
        self.voice_recognize_start_button.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.voice_recognize_button.setText(QCoreApplication.translate("MainWindow", u"\u8bed\u97f3\u8bc6\u522b", None))
        self.voice_recognize_online_icon.setText("")
        self.voice_recognize_offline_icon.setText("")
        self.voice_recognize_quit_button.setText(QCoreApplication.translate("MainWindow", u"QUIT", None))
        self.disable_win_function_title.setText(QCoreApplication.translate("MainWindow", u"\u7981\u7528Win\u529f\u80fd\u8bf4\u660e", None))
        self.disable_win_function_describe.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Agency FB'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u5728\u6e38\u620f\u8fc7\u7a0b\u4e2d\u7981\u7528Win\u952e\uff0c\u5e76\u4e14\u963b\u6b62\u8fde\u7eed\u4e24\u4e0b\u7684ctrl\u952e</p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.disable_win_describe_page), QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u8bf4\u660e", None))
        self.disable_win_startup_check.setText(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u542f\u52a8", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.disable_win_config_page), QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u914d\u7f6e", None))
        self.qq_monitor_function_title.setText(QCoreApplication.translate("MainWindow", u"QQ\u76d1\u542c\u8bf4\u660e", None))
        self.qq_monitor_function_describe.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Agency FB'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u5141\u8bb8\u76d1\u542cQQ\u4fe1\u606f\u5e76\u81ea\u52a8\u56de\u590d</p></body></html>", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.qq_monitor_describe_page), QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u8bf4\u660e", None))
        self.qq_monitor_startup_check.setText(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u542f\u52a8", None))
        self.qq_monitor_address_title.setText(QCoreApplication.translate("MainWindow", u"\u76d1\u542c\u5730\u5740\uff1a", None))
        self.qq_monitor_address_edit.setText("")
        self.qq_monitor_address_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ws://localhost:6700/api", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.qq_monitor_config_page), QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u914d\u7f6e", None))
        self.every_day_function_title.setText(QCoreApplication.translate("MainWindow", u"\u6bcf\u65e5\u68c0\u67e5\u8bf4\u660e", None))
        self.every_day_function_describe.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Agency FB'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u6bcf\u65e5\u7b2c\u4e00\u6b21\u8fd0\u884c\u65f6\uff0c\u8fdb\u884c\u6bcf\u65e5\u68c0\u67e5</p></body></html>", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.every_day_describe_page), QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u8bf4\u660e", None))
        self.every_day_startup_check.setText(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u542f\u52a8", None))
        self.blog_online_startup_check.setText(QCoreApplication.translate("MainWindow", u"\u8fdb\u884c\u535a\u5ba2\u5728\u7ebf\u68c0\u67e5", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.every_day_config_page), QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u914d\u7f6e", None))
        self.voice_recognize_function_title.setText(QCoreApplication.translate("MainWindow", u"\u8bed\u97f3\u8bc6\u522b\u8bf4\u660e", None))
        self.voice_recognize_function_describe.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Agency FB'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u957f\u6309CapsLock\u952e\uff0c\u81ea\u52a8\u76d1\u542c\u540d\u4e3a<span style=\" font-family:'\u5b8b\u4f53,monospace'; font-size:9.8pt; color:#6a8759;\">\u8f93\u5165\u9ea6\u514b\u98ce</span>\u7684\u8f93\u5165\u8bbe\u5907\uff0c\u4f7f\u7528\u963f\u91cc\u4e91API\u8fdb\u884c\u8bc6\u522b\u8f6c\u5199\uff0c\u5c06\u7ed3\u679c\u4f5c\u4e3a\u952e\u76d8\u8f93\u5165\u5230\u5f53\u524d\u5bf9\u8bdd\u6846\u4e2d</p></body></html>", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.voice_recognize_describe_page), QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u8bf4\u660e", None))
        self.voice_recognize_startup_check.setText(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u542f\u52a8", None))
        self.device_choose_label.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u8f93\u5165\u8bbe\u5907", None))
        self.ak_id_title.setText(QCoreApplication.translate("MainWindow", u"AKID:", None))
        self.ak_id_edit.setText("")
        self.ak_id_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"LTAI5t7aZE48hexQix7SgiHm", None))
        self.ak_secret_title.setText(QCoreApplication.translate("MainWindow", u"AKSECRET:", None))
        self.ak_secret_edit.setText("")
        self.ak_secret_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"w1BEw7iMmGomVtXyVp9xMUedMd7OTJ", None))
        self.app_key_title.setText(QCoreApplication.translate("MainWindow", u"APPKEY:", None))
        self.app_key_edit.setText("")
        self.app_key_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"V330NkiwzK1Jk4Xh", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.voice_recognize_config_page), QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u914d\u7f6e", None))
        self.LogTextArea.setPlainText("")
        self.auto_start_checkbox.setText(QCoreApplication.translate("MainWindow", u"\u662f\u5426\u5f00\u673a\u81ea\u542f", None))
        self.version_label.setText(QCoreApplication.translate("MainWindow", u"v1.0.0", None))
        self.version_update_button.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u5347\u7ea7", None))
        self.check_update_button.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u5347\u7ea7", None))
    # retranslateUi

