name: package and release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .\requirement.txt
          pip install pyinstaller
      - name: build with pyinstaller
        run: |
          pyinstaller .\__init__.spec

      - name: Extract some files
        run: 7z a -tzip guyu-${{ github.ref_name }}-windows-amd64.zip dist/*

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: guyu-${{ github.ref_name }}-windows-amd64.zip
          tag: ${{ github.ref_name }}
          name: Guyu ${{ github.ref_name }}
          bodyFile: RELEASE.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

# ${{ github.ref }}   guyu-refs/heads/main